// +build ignore

package sfclassic

import (
	"bytes"
	"compress/flate"
	"fmt"
	"os"

	sfold "github.com/richardlehane/siegfried"
)

func check(e error) {
	if e != nil {
		panic(e)
	}
}

func main() {
	sf, err := sfold.Load("classic/classic.sig")
	check(err)
	var buf bytes.Buffer
	z, err := flate.NewWriter(&buf, 1)
	check(err)
	err = sf.SaveWriter(z)
	check(err)
	check(z.Close())
	out, err := os.Create("signature.go")
	check(err)
	fmt.Fprintf(out, "// Code generated by go generate; DO NOT EDIT.\npackage sfclassic\n\nvar sfcontent = %#v", buf.Bytes())
	check(out.Close())
	fmt.Println("Generated a new signature.go file")
}
