package gbindata

// Reference: https://github.com/a-urth/go-bindata

import (
	"bufio"
	"encoding/hex"
	"fmt"
	"github.com/cryptowilliam/goutil/basic/gerrors"
	"github.com/cryptowilliam/goutil/container/gstring"
	"github.com/cryptowilliam/goutil/sys/gfs"
	"os"
)

var templateBegin = `
// DO NOT EDIT BY HAND
//
// Generated by bindata

package %s

var %s = "0x`

var templateEnd = `"`

// packageName: 生成的包名
// varName: 生成的包含文件数据的变量名
func Enc(binaryFilename, encodedGoFilename, packageName, varName string) error {
	if !gfs.FileExits(binaryFilename) {
		return gerrors.Errorf("file %s not exists", binaryFilename)
	}
	if !gstring.EndWith(encodedGoFilename, ".go") {
		return gerrors.Errorf("filename %s doesn't end with .go", encodedGoFilename)
	}

	os.Remove(encodedGoFilename)

	src_f, err := os.Open(binaryFilename)
	if err != nil {
		return err
	}
	defer src_f.Close()

	dst_f, err := os.Create(encodedGoFilename)
	if err != nil {
		return err
	}
	defer dst_f.Close()

	dst_f.WriteString(fmt.Sprintf(templateBegin, packageName, varName))
	scan := bufio.NewScanner(src_f)
	scan.Split(bufio.ScanBytes)
	for scan.Scan() {
		dst_f.WriteString(hex.EncodeToString(scan.Bytes()))
		if scan.Err() != nil {
			return err
		}
	}
	dst_f.WriteString(templateEnd)

	return nil
}
